apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: platformq-private-cloud
spec:
  title: platformQ Private Cloud Edition
  icon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII= # Placeholder icon
  helm:
    # This tells KOTS to use our existing umbrella chart as the application's base.
    - chart:
        name: platformq-stack
        chartVersion: 0.1.0
        # The path is relative to the root of the KOTS application bundle.
        helmVersion: v3
        path: "charts/platformq-stack" 