site_name: platformQ Reference Architecture
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
nav:
  - Home: index.md
  - "User Guides":
    - "Local Setup": "docs/local_setup.md"
  - "Architecture":
    - "Architectural Decision Records": "docs/ADR.md"
    - "Services":
      - "Authentication Service": "services/auth-service/README.md"
      - "Digital Asset Service": "services/digital-asset-service/README.md"
      - "Connector Service": "services/connector-service/README.md"
      - "Functions Service": "services/functions-service/README.md"
      - "Graph Intelligence Service": "services/graph-intelligence-service/README.md"
      - "Simulation Service": "services/simulation-service/README.md"
      - "Verifiable Credential Service": "services/verifiable-credential-service/README.md"
  - "Operator Guides":
    - "Infrastructure (Terraform)": "iac/terraform/README.md"
  - "Platform Development":
    - 'Creating a New Service': 'platformqctl/README.md' # Create this
  - 'Cloud Deployment':
    - 'Application Stack (Helm)': 'iac/kubernetes/charts/platformq-stack/README.md'
  - 'Data Pipelines (Flink)':
    - 'Activity Stream Job': 'processing/flink/activity-stream-job/README.md' # Create this
  - 'Integrations':
    - 'Nextcloud': 'docs/nextcloud_oidc_setup.md'
    - 'Zulip': 'docs/zulip_oidc_setup.md'
    - 'OpenProject': 'docs/openproject_oidc_setup.md'
  - 'API Reference':
    - 'Shared Library': 'docs/shared-lib-api/index.html'
    - 'REST APIs (OpenAPI)': 'docs/index.html' 