[tool.black]
line-length = 88
target-version = ['py311']

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I"] # Standard flake8 rules + isort
ignore = ["E501"] # Ignore line-too-long, as black handles it.

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "services/auth-service/tests",
] 