apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - platformq-gateway # Attach to our main gateway
  http:
  - match:
    - uri:
        prefix: /auth
    route:
    - destination:
        host: {{ include "auth-service.fullname" . }}
        port:
          number: 80
        # This defines the 'stable' version of our service
        subset: stable
      weight: 95 # Send 95% of traffic to the stable version
    - destination:
        host: {{ include "auth-service.fullname" . }}
        port:
          number: 80
        # This defines the 'canary' version
        subset: canary
      weight: 5 # Send 5% of traffic to the canary version
---
# We also need a DestinationRule to define the subsets (stable vs. canary)
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "auth-service.fullname" . }}
spec:
  host: {{ include "auth-service.fullname" . }}
  subsets:
  - name: stable
    labels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "auth-service.name" . }}
      # We will add a 'version' label to our pods
      version: stable
  - name: canary
    labels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ include "auth-service.name" . }}
      version: canary 