apiVersion: v1
kind: Namespace
metadata:
  name: compute-workers
---
# Base compute worker service template
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: compute-worker-base
  namespace: compute-workers
spec:
  template:
    metadata:
      annotations:
        # Auto-scaling configuration
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
        autoscaling.knative.dev/window: "60s"
        autoscaling.knative.dev/panic-window-percentage: "10.0"
        autoscaling.knative.dev/panic-threshold-percentage: "200.0"
        # Resource limits
        autoscaling.knative.dev/initial-scale: "1"
        autoscaling.knative.dev/scale-down-delay: "0s"
        autoscaling.knative.dev/stable-window: "60s"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 3600  # 1 hour timeout for long-running jobs
      containers:
      - image: platformq/compute-worker-base:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: PULSAR_URL
          value: "pulsar://pulsar.infrastructure:6650"
        - name: MINIO_URL
          value: "minio.infrastructure:9000"
        - name: IGNITE_HOST
          value: "ignite.infrastructure"
        - name: PROMETHEUS_PUSHGATEWAY_URL
          value: "pushgateway.monitoring:9091"
---
# OpenFOAM worker service
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: openfoam-worker
  namespace: compute-workers
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "1"  # One CFD job per instance
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "50"
        autoscaling.knative.dev/window: "120s"
    spec:
      containerConcurrency: 1
      timeoutSeconds: 7200  # 2 hours for CFD simulations
      containers:
      - image: platformq/openfoam-worker:latest
        resources:
          requests:
            memory: "8Gi"
            cpu: "4000m"
          limits:
            memory: "16Gi"
            cpu: "8000m"
        env:
        - name: WORKER_TYPE
          value: "openfoam"
        - name: PULSAR_URL
          value: "pulsar://pulsar.infrastructure:6650"
        - name: MINIO_URL
          value: "minio.infrastructure:9000"
---
# Blender worker service
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: blender-worker
  namespace: compute-workers
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "5"  # Multiple render jobs per instance
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "200"  # High scale for render farm
        autoscaling.knative.dev/window: "30s"
        # GPU node selector for rendering
        feature.node.kubernetes.io/gpu: "true"
    spec:
      containerConcurrency: 5
      timeoutSeconds: 3600
      nodeSelector:
        accelerator: nvidia-gpu
      containers:
      - image: platformq/blender-worker:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
            nvidia.com/gpu: "1"
          limits:
            memory: "8Gi"
            cpu: "4000m"
            nvidia.com/gpu: "1"
        env:
        - name: WORKER_TYPE
          value: "blender"
        - name: ENABLE_GPU
          value: "true"
---
# FlightGear worker service
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: flightgear-worker
  namespace: compute-workers
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "2"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 2
      timeoutSeconds: 3600
      containers:
      - image: platformq/flightgear-worker:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        env:
        - name: WORKER_TYPE
          value: "flightgear"
---
# FreeCAD worker service
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: freecad-worker
  namespace: compute-workers
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "3"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "50"
    spec:
      containerConcurrency: 3
      timeoutSeconds: 3600
      containers:
      - image: platformq/freecad-worker:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "4000m"
        env:
        - name: WORKER_TYPE
          value: "freecad"
---
# Media processing workers (GIMP, OpenShot, Audacity)
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: media-worker
  namespace: compute-workers
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/class: "kpa.autoscaling.knative.dev"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "10"
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 1800
      containers:
      - image: platformq/media-worker:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: WORKER_TYPE
          value: "media" 