{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "compute-allocation-service.fullname" . }}
  labels:
    {{- include "compute-allocation-service.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "compute-allocation-service.selectorLabels" . | nindent 6 }}
{{- end }} 