groups:
  - name: platformq-alerts
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: page
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
          
      - alert: HighErrorRate
        expr: (sum(rate(http_server_requests_seconds_count{status_code=~"5..", job="otel-collector"}[5m])) / sum(rate(http_server_requests_seconds_count{job="otel-collector"}[5m]))) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP Error Rate on {{ $labels.service_name }}"
          description: "Service {{ $labels.service_name }} has an error rate above 5% for the last 5 minutes." 