_format_version: "2.1"
_comment: "Declarative Kong configuration for platformQ"

services:
  - name: auth-service
    url: http://auth-service:8000
    routes:
      - name: auth-routes
        paths:
          - /auth
      - name: auth-docs
        paths:
          - /auth/docs
          - /auth/redoc
  - name: digital-asset-service
    url: http://digital-asset-service:8000
    routes:
      - name: digital-asset-routes
        paths:
          - /digital-assets
      - name: digital-asset-docs
        paths:
          - /digital-assets/docs
          - /digital-assets/redoc
  - name: storage-proxy-service
    url: http://storage-proxy-service:8000
    routes:
      - name: storage-proxy-routes
        paths:
          - /storage
      - name: storage-proxy-docs
        paths:
          - /storage/docs
          - /storage/redoc
  - name: verifiable-credential-service
    url: http://verifiable-credential-service:8000
    routes:
      - name: vc-routes
        paths:
          - /vc
      - name: vc-docs
        paths:
          - /vc/docs
          - /vc/redoc

plugins:
  - name: rate-limiting
    service: auth-service
    config:
      minute: 100
      policy: local
  - name: rate-limiting
    service: digital-asset-service
    config:
      minute: 100
      policy: local 

consumers:
  - username: end-users
  - username: internal-services

acls:
  - consumer: end-users
    group: public-routes
  - consumer: internal-services
    group: internal-routes

routes:
  - name: auth-routes-public
    paths:
      - /auth/api/v1/siwe/nonce
      - /auth/api/v1/siwe/login
    plugins:
      - name: acl
        config:
          whitelist:
            - public-routes
  - name: auth-routes-internal
    paths:
      - /auth/api/v1/internal
    plugins:
      - name: acl
        config:
          whitelist:
            - internal-routes 