# Default values for unified-data-service
replicaCount: 2

image:
  repository: platformq/unified-data-service
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 8000
  targetPort: 8000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: unified-data.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - unified-data-service
        topologyKey: kubernetes.io/hostname

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Environment variables
env:
  - name: SERVICE_NAME
    value: unified-data-service
  - name: PORT
    value: "8000"
  - name: LOG_LEVEL
    value: INFO
  
  # Trino Configuration
  - name: TRINO_HOST
    value: trino-coordinator
  - name: TRINO_PORT
    value: "8080"
  - name: TRINO_USER
    value: platformq
  
  # Apache Ignite
  - name: IGNITE_HOST
    value: ignite-1
  - name: IGNITE_PORT
    value: "10800"
  
  # Pulsar
  - name: PULSAR_URL
    value: pulsar://pulsar:6650
  
  # Database
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: unified-data-secrets
        key: database-url
  
  # Apache Atlas (Optional)
  - name: ATLAS_URL
    value: http://atlas:21000
  - name: ATLAS_USERNAME
    valueFrom:
      secretKeyRef:
        name: unified-data-secrets
        key: atlas-username
        optional: true
  - name: ATLAS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: unified-data-secrets
        key: atlas-password
        optional: true
  
  # Apache Ranger (Optional)
  - name: RANGER_URL
    value: http://ranger:6080
  - name: RANGER_USERNAME
    valueFrom:
      secretKeyRef:
        name: unified-data-secrets
        key: ranger-username
        optional: true
  - name: RANGER_PASSWORD
    valueFrom:
      secretKeyRef:
        name: unified-data-secrets
        key: ranger-password
        optional: true

# Volume mounts
volumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: cache
    mountPath: /app/.cache

volumes:
  - name: tmp
    emptyDir: {}
  - name: cache
    emptyDir: {}

# Service mesh configuration
serviceMesh:
  enabled: true
  virtualService:
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
  destinationRule:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 100
        http2MaxRequests: 100

# Monitoring
monitoring:
  enabled: true
  prometheus:
    enabled: true
    path: /metrics
    port: 8000
  
  serviceMonitor:
    enabled: true
    interval: 30s
    path: /metrics
    labels:
      release: prometheus

# PodDisruptionBudget
podDisruptionBudget:
  enabled: true
  minAvailable: 1 