apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mlflow-vs
spec:
  hosts:
  - "*"
  gateways:
  - platformq-gateway # Attach to our main gateway
  http:
  - match:
    - uri:
        prefix: /mlflow
    route:
    - destination:
        host: platformq-mlflow # The internal Kubernetes service name for MLflow
        port:
          number: 5000 # Default MLflow port 