apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  # Apply this policy to all workloads in the namespace
  mtls:
    # Enforce strict mutual TLS. All traffic between services in the mesh
    # MUST be encrypted.
    mode: STRICT 