apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    # This label tells the Istio control plane to automatically
    # inject the Envoy proxy sidecar into all pods in this namespace.
    istio-injection: enabled 