apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: onlyoffice-docs-vs
spec:
  hosts:
  - "*"
  gateways:
  - platformq-gateway # Attach to our main gateway
  http:
  - match:
    - uri:
        prefix: /onlyoffice/
    route:
    - destination:
        host: platformq-onlyoffice-docs # The internal Kubernetes service name
        port:
          number: 80 