apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: platformq-custom-rules
  labels:
    app: kube-prometheus-stack
    release: platformq # This matches the selector in values.yaml
spec:
  groups:
    - name: platformq-alerts
      rules:
        - alert: InstanceDown
          expr: up == 0
          for: 1m
          labels:
            severity: page
          annotations:
            summary: "Instance {{ $labels.instance }} down"
            description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."
            
        - alert: HighErrorRate
          expr: (sum(rate(http_server_requests_seconds_count{status_code=~"5..", job="otel-collector"}[5m])) / sum(rate(http_server_requests_seconds_count{job="otel-collector"}[5m]))) > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "High HTTP Error Rate on {{ $labels.service_name }}"
            description: "Service {{ $labels.service_name }} has an error rate above 5% for the last 5 minutes." 
    - name: platformq-slos
      rules:
      - record: job_method_path:http_requests:rate5m
        expr: sum(rate(http_server_requests_seconds_count[5m])) by (job, method, path)

      # --- Auth Service Latency SLO (95% < 200ms) ---
      - record: job:http_requests_bucket:rate_28d
        expr: sum(rate(http_server_requests_seconds_bucket{service_name="auth-service", path="/api/v1/token"}[28d])) by (le)
      - record: job:http_requests_total:rate_28d
        expr: sum(rate(http_server_requests_seconds_count{service_name="auth-service", path="/api/v1/token"}[28d]))

      - alert: AuthTokenLatencyBudgetBurningTooFast
        expr: (sum(rate(http_server_requests_seconds_bucket{service_name="auth-service", path="/api/v1/token", le="0.2"}[1h])) / sum(rate(http_server_requests_seconds_count{service_name="auth-service", path="/api/v1/token"}[1h]))) < 0.95
        for: 2m
        labels:
          severity: warning
          slo: "true"
        annotations:
          summary: "Auth Service Token Latency SLO Error Budget is burning too fast"
          description: "More than 5% of requests to the token endpoint have been slower than 200ms over the last hour."

      # --- Auth Service Availability SLO (99.9% success) ---
      - record: job:http_requests_error_total:rate_28d
        expr: sum(rate(http_server_requests_seconds_count{service_name="auth-service", path="/api/v1/token", status_code=~"5.."}[28d]))
      
      - alert: AuthTokenAvailabilityBudgetBurningTooFast
        expr: (sum(rate(http_server_requests_seconds_count{service_name="auth-service", path="/api/v1/token", status_code=~"5.."}[1h])) / sum(rate(http_server_requests_seconds_count{service_name="auth-service", path="/api/v1/token"}[1h]))) > (0.001 * 14)
        for: 5m
        labels:
          severity: critical
          slo: "true"
        annotations:
          summary: "Auth Service Token Availability SLO Error Budget is burning too fast"
          description: "The error rate for the token endpoint is high enough that it will violate the 99.9% SLO if it continues." 