apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/platformq-gateway
  http:
  - match:
    - uri:
        prefix: /connector-service
    route:
    - destination:
        host: {{ .Release.Name }}
        port:
          number: {{ .Values.service.port }}
