# Default values for auth-service chart.
replicaCount: 1

image:
  repository: your-docker-registry/verifiable-credential-service # CHANGE THIS
  pullPolicy: IfNotPresent
  tag: "latest"
  stable:
    tag: "latest"
  canary:
    tag: "latest"
    replicaCount: 1

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false # Disabled by default for new services
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80 # Can also scale on memory

# We don't need to define resources, ingresses, etc. for this basic chart,
# as Kong will handle external access. 