
"""add asset_processing_rules table

Revision ID: 1234567890
Revises: 
Create Date: 2023-10-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1234567890'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.create_table('asset_processing_rules',
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('wasm_module_id', sa.String(), nullable=False, comment='The ID/name of the WASM module in the functions-service'),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_by_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('asset_type')
    )
    op.create_index(op.f('ix_asset_processing_rules_asset_type'), 'asset_processing_rules', ['asset_type'], unique=False)
    op.create_index(op.f('ix_asset_processing_rules_tenant_id'), 'asset_processing_rules', ['tenant_id'], unique=False)
    
    op.create_foreign_key('fk_digital_assets_asset_type_asset_processing_rules', 'digital_assets', 'asset_processing_rules', ['asset_type'], ['asset_type'])
    op.create_index(op.f('ix_digital_assets_asset_type'), 'digital_assets', ['asset_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto-generated by Alembic - please adjust! ###
    op.drop_constraint('fk_digital_assets_asset_type_asset_processing_rules', 'digital_assets', type_='foreignkey')
    op.drop_index(op.f('ix_digital_assets_asset_type'), table_name='digital_assets')

    op.drop_index(op.f('ix_asset_processing_rules_tenant_id'), table_name='asset_processing_rules')
    op.drop_index(op.f('ix_asset_processing_rules_asset_type'), table_name='asset_processing_rules')
    op.drop_table('asset_processing_rules')
    # ### end Alembic commands ### 