apiVersion: v2
name: federated-learning-service
description: Privacy-preserving federated learning coordinator service
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami 