replicaCount: 2

image:
  repository: platformq/federated-learning-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "federated-learning-service"

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: federated-learning.platformq.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: federated-learning-tls
      hosts:
        - federated-learning.platformq.io

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - federated-learning-service
        topologyKey: kubernetes.io/hostname

env:
  - name: SERVICE_NAME
    value: "federated-learning-service"
  - name: PULSAR_URL
    value: "pulsar://pulsar-broker:6650"
  - name: VC_SERVICE_URL
    value: "http://verifiable-credential-service:80"
  - name: AUTH_SERVICE_URL
    value: "http://auth-service:80"
  - name: SPARK_MASTER_URL
    value: "spark://spark-master:7077"
  - name: IGNITE_NODES
    value: "ignite-0.ignite:10800,ignite-1.ignite:10800,ignite-2.ignite:10800"
  - name: MINIO_ENDPOINT
    value: "http://minio:9000"
  - name: ELASTICSEARCH_URL
    value: "http://elasticsearch:9200"
  - name: LOG_LEVEL
    value: "INFO"

secrets:
  - name: MINIO_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: access-key
  - name: MINIO_SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: minio-credentials
        key: secret-key

# Spark job submission configuration
spark:
  enabled: true
  executor:
    instances: 4
    memory: "4g"
    cores: 4
  driver:
    memory: "2g"
    cores: 2
  
# Ignite client configuration  
ignite:
  clientMode: true
  connectionTimeout: 10000
  
# Privacy configuration defaults
privacy:
  defaultEpsilon: 1.0
  defaultDelta: 0.00001
  maxRounds: 50
  minParticipants: 2
  
# Model storage
storage:
  modelBucket: "federated-learning"
  retentionDays: 90 