# Default values for auth-service chart.
replicaCount: 1

image:
  repository: your-docker-registry/auth-service # CHANGE THIS
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80 # Can also scale on memory

# We don't need to define resources, ingresses, etc. for this basic chart,
# as Kong will handle external access. 