apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "federated-learning-service.fullname" . }}-spark-config
  labels:
    {{- include "federated-learning-service.labels" . | nindent 4 }}
data:
  spark-defaults.conf: |
    spark.master                     {{ .Values.env | include "getEnvValue" "SPARK_MASTER_URL" }}
    spark.submit.deployMode          cluster
    spark.executor.instances         {{ .Values.spark.executor.instances }}
    spark.executor.memory            {{ .Values.spark.executor.memory }}
    spark.executor.cores             {{ .Values.spark.executor.cores }}
    spark.driver.memory              {{ .Values.spark.driver.memory }}
    spark.driver.cores               {{ .Values.spark.driver.cores }}
    spark.sql.adaptive.enabled       true
    spark.sql.adaptive.coalescePartitions.enabled true
    spark.serializer                 org.apache.spark.serializer.KryoSerializer
    spark.kryo.registrationRequired  false
    
    # Ignite integration
    spark.ignite.servers             {{ .Values.env | include "getEnvValue" "IGNITE_NODES" }}
    
    # S3/MinIO configuration
    spark.hadoop.fs.s3a.endpoint     {{ .Values.env | include "getEnvValue" "MINIO_ENDPOINT" }}
    spark.hadoop.fs.s3a.access.key   ${MINIO_ACCESS_KEY}
    spark.hadoop.fs.s3a.secret.key   ${MINIO_SECRET_KEY}
    spark.hadoop.fs.s3a.path.style.access true
    spark.hadoop.fs.s3a.impl         org.apache.hadoop.fs.s3a.S3AFileSystem
    
    # ML configuration
    spark.ml.tuning.parallelism      4
    
{{/*
Helper to extract env value
*/}}
{{- define "getEnvValue" -}}
{{- $envName := . -}}
{{- range $.Values.env -}}
{{- if eq .name $envName -}}
{{- .value -}}
{{- end -}}
{{- end -}}
{{- end -}} 